### ISSUE TITLE
项目运行不起来

### ISSUE THREAD

**Issue by monster-Lucas** [zzh948498/RuoYi-Vue3-ts#1]
不知道是node版本问题还是什么问题 ，有 Cannot find module 'node:fs'的报错

**Comment by zzh948498** [comment]
需要 [Node.js](https://nodejs.org/en/) 版本 14.18+，16+。然而，有些模板需要依赖更高的 Node 版本才能正常运行，当你的包管理器发出警告时，请注意升级你的 Node 版本。

**Comment by zzh948498** [comment]
> 不知道是node版本问题还是什么问题 ，有 Cannot find module 'node:fs'的报错

需要 [Node.js](https://nodejs.org/en/) 版本 14.18+，16+。然而，有些模板需要依赖更高的 Node 版本才能正常运行，当你的包管理器发出警告时，请注意升级你的 Node 版本。
