### ISSUE TITLE
角色管理/system/role新增和修改按钮点击报错

### ISSUE THREAD

**Issue by authshuker** [zzh948498/RuoYi-Vue3-ts#3]
/** 重置新增的表单以及其他数据  */
function reset() {
    if (menuRef.value !== undefined) {   //menuRef.value可能是null
        menuRef.value.setCheckedKeys([]);
    }
    menuExpand.value = false;
    menuNodeAll.value = false;
    deptExpand.value = true;
    deptNodeAll.value = false;
    form.value = {
        roleId: undefined,
        roleName: undefined,
        roleKey: undefined,
        roleSort: 0,
        status: '0',
        menuIds: [],
        deptIds: [],
        menuCheckStrictly: true,
        deptCheckStrictly: true,
        remark: undefined,
    };
    proxy!.resetForm('roleRef');
}

**Comment by zzh948498** [comment]
感谢分享
