### ISSUE TITLE
自动生成的代码，前端是vue2.x的，不是3.0的，且新增按钮，点击后无效果

### ISSUE THREAD

**Issue by DreamapleHT** [zzh948498/RuoYi-Vue3-ts#6]

**Comment by zzh948498** [comment]
配套的vue3代码生成模板
https://gitee.com/y_project/RuoYi-Vue/tree/master/ruoyi-generator/src/main/resources/vm/vue/v3
代码生成参考
http://doc.ruoyi.vip/ruoyi/document/htsc.html#%E4%BB%A3%E7%A0%81%E7%94%9F%E6%88%90
