### ISSUE TITLE
服了

### ISSUE THREAD

**Issue by jess-zz** [zzh948498/RuoYi-Vue3-ts#7]
你搁着这anyScript 呢。。。

**Comment by zzh948498** [comment]
> 你搁着这anyScript呢。。。

我只是把公用部分类型加上了，有一些接口细节我确实不知道每个字段都是干嘛的

**Comment by zzh948498** [comment]
> 你搁着这anyScript 呢。。。

我只是把公用部分类型加上了，有一些接口细节我确实不知道每个字段都是干嘛的

你觉得不合适可以为开源提交PR

**Comment by zzh948498** [comment]
> 你搁着这anyScript 呢。。。

公共类型或者改动较少的类型我可以加上，像大部分接口，ruoyi官方随时修改字段，我不写any写什么

你在二开时可以把你想要的类型加上
